version: '2'
services:
    twpoints-app:
        image: twpoints
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://twpoints-mysql:3306/twpoints?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    twpoints-mysql:
        extends:
            file: mysql.yml
            service: twpoints-mysql
